#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XSLT
version:      0.48
version_from: lib/XML/XSLT.pm
installdirs:  site
requires:
    Test::More:                    0.33
    XML::DOM:                      1.25
    XML::Parser:                   2.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
