#!/usr/bin/perl -w -Iblib/lib

use XML::XSLT;
use Getopt::Std;

my %opt;
my $usage = "Usage: $0 [options] <project>

  -d[ebug]		turn debugging mode on
  -n[oweb]		don't print content-type
  -s[tylesheet] <file>	use <file> instead of <project>.xsl as template
  -w[arnings]		turns warnings on\n";
getopts('dnws:', \%opt) || die $usage;

## global vars ##
my $noweb = $opt{n} || 0;
my $debug = $opt{d} || 0;
my $warnings = $opt{w} || 0;
my $project = shift || die $usage;
my $xslfile = $opt{'s'} || "$project.xsl";
my $xmlfile = "$project.xml";

my $xslt = XML::XSLT->new (Source   => $xslfile,
			   debug    => $debug,
			   warnings => $debug);
$xslt->transform($xmlfile);

print STDERR qq{Debug   : "$debug"
NoWeb   : "$noweb"
Warnings: "$warnings"
Project : "$project"
XML-file: "$xmlfile"
XSL-file: "$xslfile"
} if $debug;

print "Content-type: text/html\n\n" unless $noweb;
print $xslt->asString;
