#!/usr/local/bin/perl -w

if (!@ARGV) {
    die "Usage: $0 [options] <project>$/$/  -d[ebug]\t\tturn debugging mode on$/  -n[oweb]\t\tdon't print content-type$/  -s[tylesheet] <file>\tuse <file> instead of <project>.xsl as template$/  -w[arnings]\t\tturns warnings on$/";
}

use XML::XSLT;

## global vars ##
my $noweb = ""; # False #
my $debug = ""; # False #
my $warnings = "Active";
my $project = "";
my $xslfile = "";
my $xmlfile = "";

&process_arguments (@ARGV);
print $/ if $debug;

my $XSLTparser = XML::XSLT->new ($xslfile, "FILE", debug => $debug, warnings => $warnings);
$XSLTparser->transform_document ($xmlfile, "FILE");
print "Content-type: text/html$/$/" unless $noweb;
$XSLTparser->print_result();

exit;


sub process_arguments {
  my @argv = @_;
  if (@argv) {
    while ((@argv > 1) && ($argv[0] =~ /^\-/)) {
      my $param = shift @argv;

      $debug = "active" if ($param =~ /^\-d/i);
      $noweb = "active" if ($param =~ /^\-n/i);
      $warnings = "active" if ($param =~ /^\-w/i);
      if (($param =~ /^\-s/i) && ((@argv > 1) && ($argv[0] !~ /^\-/))) {
        $param = shift (@argv);
        $xslfile = $param;
      }

      $noweb = "" if $debug;
      $warnings = "" if $debug;

    }

    print "Content-type: text/html$/$/" if $debug;
    print "Debug   : \"",$debug,"\"$/NoWeb   : \"$noweb\"$/Warnings: \"",$warnings,"\"$/" if $debug;

    if (@argv && ($argv[0] !~ /^\-/)) {
      $project = shift (@argv);
      $xmlfile = "$project.xml";
      $xslfile = "$project.xsl" unless $xslfile;
      die "Error: could not open $xmlfile, make sure it exists.$/" if (! (-f $xmlfile));
      die "Error: could not open $xslfile, make sure it exists.$/" if (! (-f $xslfile));
    } else {
      die "Error: no project specified, give a name of a project.$/";
    }
    print "Project : \"",$project,"\"$/  XML-file: \"$xmlfile\"$/  XSL-file: \"$xslfile\"$/" if $debug;
  } else {
    die "Usage: $0 [options] <project>$/$/  -d[ebug]\t\tturn debugging mode on$/  -n[oweb]\t\tdon't print content-type$/  -s[tylesheet] <file>\tuse <file> instead of <project>.xsl as template$/  -w[arnings]\t\tturns warnings on$/";
  }
}
